In [1]:
import numpy as np 
import pandas as pd
import sqlite3
import matplotlib.pyplot as plt

conn = sqlite3.connect('database.sqlite')

tables = pd.read_sql(
    """SELECT * 
       FROM sqlite_master
       WHERE type='table';""", conn)

tables

type               name           tbl_name  rootpage  \
0  table    sqlite_sequence    sqlite_sequence         4   
1  table  Player_Attributes  Player_Attributes        11   
2  table             Player             Player        14   
3  table              Match              Match        18   
4  table             League             League        24   
5  table            Country            Country        26   
6  table               Team               Team        29   
7  table    Team_Attributes    Team_Attributes         2   

                                                 sql  
0             CREATE TABLE sqlite_sequence(name,seq)  
1  CREATE TABLE "Player_Attributes" (\n\t`id`\tIN...  
2  CREATE TABLE `Player` (\n\t`id`\tINTEGER PRIMA...  
3  CREATE TABLE `Match` (\n\t`id`\tINTEGER PRIMAR...  
4  CREATE TABLE `League` (\n\t`id`\tINTEGER PRIMA...  
5  CREATE TABLE `Country` (\n\t`id`\tINTEGER PRIM...  
6  CREATE TABLE "Team" (\n\t`id`\tINTEGER PRIMARY...  
7  CREATE TABLE `Team_Attributes` (\n\t`id`\tINTE...

In [2]:
# database sqlite_sequence - nothing useful
sqlite_sequence = pd.read_sql(
    """SELECT * FROM sqlite_sequence;""", conn)

sqlite_sequence

name     seq
0               Team  103916
1            Country   51958
2             League   51958
3              Match   51958
4             Player   11075
5  Player_Attributes  183978
6    Team_Attributes    1458

In [3]:
# database Player_Attributes
player_attributes = pd.read_sql(
    """SELECT * FROM Player_Attributes;""", conn)

player_attributes

id  player_fifa_api_id  player_api_id                 date  \
0            1              218353         505942  2016-02-18 00:00:00   
1            2              218353         505942  2015-11-19 00:00:00   
2            3              218353         505942  2015-09-21 00:00:00   
3            4              218353         505942  2015-03-20 00:00:00   
4            5              218353         505942  2007-02-22 00:00:00   
...        ...                 ...            ...                  ...   
183973  183974              102359          39902  2009-08-30 00:00:00   
183974  183975              102359          39902  2009-02-22 00:00:00   
183975  183976              102359          39902  2008-08-30 00:00:00   
183976  183977              102359          39902  2007-08-30 00:00:00   
183977  183978              102359          39902  2007-02-22 00:00:00   

        overall_rating  potential preferred_foot attacking_work_rate  \
0                 67.0       71.0          right              medium   
1                 67.0       71.0          right              medium   
2                 62.0       66.0          right              medium   
3                 61.0       65.0          right              medium   
4                 61.0       65.0          right              medium   
...                ...        ...            ...                 ...   
183973            83.0       85.0          right              medium   
183974            78.0       80.0          right              medium   
183975            77.0       80.0          right              medium   
183976            78.0       81.0          right              medium   
183977            80.0       81.0          right              medium   

       defensive_work_rate  crossing  ...  vision  penalties  marking  \
0                   medium      49.0  ...    54.0       48.0     65.0   
1                   medium      49.0  ...    54.0       48.0     65.0   
2                   medium      49.0  ...    54.0       48.0     65.0   
3                   medium      48.0  ...    53.0       47.0     62.0   
4                   medium      48.0  ...    53.0       47.0     62.0   
...                    ...       ...  ...     ...        ...      ...   
183973                 low      84.0  ...    88.0       83.0     22.0   
183974                 low      74.0  ...    88.0       70.0     32.0   
183975                 low      74.0  ...    88.0       70.0     32.0   
183976                 low      74.0  ...    88.0       53.0     28.0   
183977                 low      74.0  ...    88.0       53.0     38.0   

        standing_tackle  sliding_tackle  gk_diving  gk_handling  gk_kicking  \
0                  69.0            69.0        6.0         11.0        10.0   
1                  69.0            69.0        6.0         11.0        10.0   
2                  66.0            69.0        6.0         11.0        10.0   
3                  63.0            66.0        5.0         10.0         9.0   
4                  63.0            66.0        5.0         10.0         9.0   
...                 ...             ...        ...          ...         ...   
183973             31.0            30.0        9.0         20.0        84.0   
183974             31.0            30.0        9.0         20.0        73.0   
183975             31.0            30.0        9.0         20.0        73.0   
183976             32.0            30.0        9.0         20.0        73.0   
183977             32.0            30.0        9.0          9.0        78.0   

        gk_positioning  gk_reflexes  
0                  8.0          8.0  
1                  8.0          8.0  
2                  8.0          8.0  
3                  7.0          7.0  
4                  7.0          7.0  
...                ...          ...  
183973            20.0         20.0  
183974            20.0         20.0  
183975            20.0         20.0  
183976            20.0         20.0  
183977        

In [4]:
player_attributes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183978 entries, 0 to 183977
Data columns (total 42 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   id                   183978 non-null  int64  
 1   player_fifa_api_id   183978 non-null  int64  
 2   player_api_id        183978 non-null  int64  
 3   date                 183978 non-null  object 
 4   overall_rating       183142 non-null  float64
 5   potential            183142 non-null  float64
 6   preferred_foot       183142 non-null  object 
 7   attacking_work_rate  180748 non-null  object 
 8   defensive_work_rate  183142 non-null  object 
 9   crossing             183142 non-null  float64
 10  finishing            183142 non-null  float64
 11  heading_accuracy     183142 non-null  float64
 12  short_passing        183142 non-null  float64
 13  volleys              181265 non-null  float64
 14  dribbling            183142 non-null  float64
 15  curve            

Перелік даних включає наступні характеристики футбольних гравців:

* id - Ідентифікатор
* player_fifa_api_id - Ідентифікатор гравця в системі FIFA
* player_api_id - Ідентифікатор гравця в системі
* date - Дата запису даних
* overall_rating - Загальна оцінка
* potential - Потенціал
* preferred_foot - Вибрана нога
* attacking_work_rate - Рівень атакуючої активності
* defensive_work_rate - Рівень оборонної активності
* crossing - Передачі з-за голови
* finishing - Завершення атак
* heading_accuracy - Заголовки
* short_passing - Короткі передачі
* volleys - Удари "півволе"
* dribbling - Дріблінг
* curve - Крива передачі
* free_kick_accuracy - Меткість при штрафних ударами
* long_passing - Дальні передачі
* ball_control - Володіння м'ячем
* acceleration - Прискорення
* sprint_speed - Спринт
* agility - Ловкість
* reactions - Реакції
* balance - Баланс
* shot_power - Сила удару
* jumping - Прижки
* stamina - Витривалість
* strength - Сила
* long_shots - Дальні удари
* aggression - Агресія
* interceptions - Перехоплення
* positioning - Позиціонування
* vision - Огляд гри
* penalties - Удари з пенальті
* marking - Маркування
* standing_tackle - Стійка в відборі
* sliding_tackle - Ковзання в відборі
* gk_diving - Прижки воротаря
* gk_handling - Володіння м'ячем воротаря
* gk_kicking - Вивід м'яча воротарем
* gk_positioning - Позиціонування воротаря
* gk_reflexes - Рефлекси воротаря

In [5]:
for column in player_attributes.columns:
    unique_values = player_attributes[column].unique()
    print(f"Унікальні значення в колонці {column}:\n{unique_values}\n")


Унікальні значення в колонці id:
[     1      2      3 ... 183976 183977 183978]

Унікальні значення в колонці player_fifa_api_id:
[218353 189615 186170 ... 111191  47058 102359]

Унікальні значення в колонці player_api_id:
[505942 155782 162549 ...  36491  35506  39902]

Унікальні значення в колонці date:
['2016-02-18 00:00:00' '2015-11-19 00:00:00' '2015-09-21 00:00:00'
 '2015-03-20 00:00:00' '2007-02-22 00:00:00' '2016-04-21 00:00:00'
 '2016-04-07 00:00:00' '2016-01-07 00:00:00' '2015-12-24 00:00:00'
 '2015-12-17 00:00:00' '2015-10-16 00:00:00' '2015-09-25 00:00:00'
 '2015-01-09 00:00:00' '2014-12-05 00:00:00' '2014-11-07 00:00:00'
 '2014-09-18 00:00:00' '2014-05-02 00:00:00' '2014-04-04 00:00:00'
 '2014-03-14 00:00:00' '2013-12-13 00:00:00' '2013-11-08 00:00:00'
 '2013-10-04 00:00:00' '2013-09-20 00:00:00' '2013-05-03 00:00:00'
 '2013-03-22 00:00:00' '2013-03-15 00:00:00' '2013-02-22 00:00:00'
 '2013-02-15 00:00:00' '2012-08-31 00:00:00' '2012-02-22 00:00:00'
 '2011-08-30 00:00:00'

In [7]:
# database player
player = pd.read_sql(
    """SELECT * FROM Player;""", conn)

player

id  player_api_id          player_name  player_fifa_api_id  \
0          1         505942   Aaron Appindangoye              218353   
1          2         155782      Aaron Cresswell              189615   
2          3         162549          Aaron Doran              186170   
3          4          30572        Aaron Galindo              140161   
4          5          23780         Aaron Hughes               17725   
...      ...            ...                  ...                 ...   
11055  11071          26357       Zoumana Camara                2488   
11056  11072         111182         Zsolt Laczko              164680   
11057  11073          36491            Zsolt Low              111191   
11058  11074          35506  Zurab Khizanishvili               47058   
11059  11075          39902   Zvjezdan Misimovic              102359   

                  birthday  height  weight  
0      1992-02-29 00:00:00  182.88     187  
1      1989-12-15 00:00:00  170.18     146  
2      1991-05-13 00:00:00  170.18     163  
3      1982-05-08 00:00:00  182.88     198  
4      1979-11-08 00:00:00  182.88     154  
...                    ...     ...     ...  
11055  1979-04-03 00:00:00  182.88     168  
11056  1986-12-18 00:00:00  182.88     176  
11057  1979-04-29 00:00:00  180.34     154  
11058  1981-10-06 00:00:00  185.42     172  
11059  1982-06-05 00:00:00  180.34     176  

[11060 rows x 7 columns]

In [8]:
player.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11060 entries, 0 to 11059
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   id                  11060 non-null  int64  
 1   player_api_id       11060 non-null  int64  
 2   player_name         11060 non-null  object 
 3   player_fifa_api_id  11060 non-null  int64  
 4   birthday            11060 non-null  object 
 5   height              11060 non-null  float64
 6   weight              11060 non-null  int64  
dtypes: float64(1), int64(4), object(2)
memory usage: 605.0+ KB


In [10]:
# database match
match = pd.read_sql(
    """SELECT * FROM Match;""", conn)

match

id  country_id  league_id     season  stage                 date  \
0          1           1          1  2008/2009      1  2008-08-17 00:00:00   
1          2           1          1  2008/2009      1  2008-08-16 00:00:00   
2          3           1          1  2008/2009      1  2008-08-16 00:00:00   
3          4           1          1  2008/2009      1  2008-08-17 00:00:00   
4          5           1          1  2008/2009      1  2008-08-16 00:00:00   
...      ...         ...        ...        ...    ...                  ...   
25974  25975       24558      24558  2015/2016      9  2015-09-22 00:00:00   
25975  25976       24558      24558  2015/2016      9  2015-09-23 00:00:00   
25976  25977       24558      24558  2015/2016      9  2015-09-23 00:00:00   
25977  25978       24558      24558  2015/2016      9  2015-09-22 00:00:00   
25978  25979       24558      24558  2015/2016      9  2015-09-23 00:00:00   

       match_api_id  home_team_api_id  away_team_api_id  home_team_goal  ...  \
0            492473              9987              9993               1  ...   
1            492474             10000              9994               0  ...   
2            492475              9984              8635               0  ...   
3            492476              9991              9998               5  ...   
4            492477              7947              9985               1  ...   
...             ...               ...               ...             ...  ...   
25974       1992091             10190             10191               1  ...   
25975       1992092              9824             10199               1  ...   
25976       1992093              9956             10179               2  ...   
25977       1992094              7896             10243               0  ...   
25978       1992095             10192              9931               4  ...   

        SJA   VCH   VCD   VCA   GBH   GBD   GBA   BSH   BSD   BSA  
0      4.00  1.65  3.40  4.50  1.78  3.25  4.00  1.73  3.40  4.20  
1      3.80  2.00  3.25  3.25  1.85  3.25  3.75  1.91  3.25  3.60  
2      2.50  2.35  3.25  2.65  2.50  3.20  2.50  2.30  3.20  2.75  
3      7.50  1.45  3.75  6.50  1.50  3.75  5.50  1.44  3.75  6.50  
4      1.73  4.50  3.40  1.65  4.50  3.50  1.65  4.75  3.30  1.67  
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
25974   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
25975   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
25976   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
25977   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
25978   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[25979 rows x 115 columns]

* 1. Аналіз перемог, якщо матч "вдома" або "на виїзді"

* 2. Залежність перемоги від воротарів
- аналіз кількості перемог коли воротар Хосе Мануэль Пінто(2008-2014)
- аналіз кількості перемог коли воротар Рубен Міньо(2010-2012)
- аналіз кількості перемог коли воротар Клаудіо Браво(2014-2016)

* АБО купили в якомусь році "дорогого" ігрока, як змінилася кількість перемог в роки після цього(корисний чи ні) - знатоки футбола потрібна допомога

* АБО зміна тренера в якомусь році - аналіз перемог(перемога, поразка, нічия) за кожного наступного тренера по рокам(самий ефективний тренер)
   
* 3. Залежність перемог від суперника(наприклад в грі з Granada CF - 70% поразка, з CD Numancia - 20%)

* 4. Зміна поля для тренування(вплив на фіз підготовку) в якомусь році - з ....року почали більше програвати

In [12]:
match.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25979 entries, 0 to 25978
Columns: 115 entries, id to BSA
dtypes: float64(96), int64(9), object(10)
memory usage: 22.8+ MB


In [13]:
for column in match.columns:
    unique_values = match[column].unique()
    print(f"Унікальні значення в колонці {column}:\n{unique_values}\n")

Унікальні значення в колонці id:
[    1     2     3 ... 25977 25978 25979]

Унікальні значення в колонці country_id:
[    1  1729  4769  7809 10257 13274 15722 17642 19694 21518 24558]

Унікальні значення в колонці league_id:
[    1  1729  4769  7809 10257 13274 15722 17642 19694 21518 24558]

Унікальні значення в колонці season:
['2008/2009' '2009/2010' '2010/2011' '2011/2012' '2012/2013' '2013/2014'
 '2014/2015' '2015/2016']

Унікальні значення в колонці stage:
[ 1 10 11 12 13 14 15 16 17 18 19  2 20 21 22 23 24 25 26 27 28 29  3 30
 31 32 33 34  4  5  6  7  8  9 35 36 37 38]

Унікальні значення в колонці date:
['2008-08-17 00:00:00' '2008-08-16 00:00:00' '2008-09-24 00:00:00' ...
 '2016-05-22 00:00:00' '2016-05-25 00:00:00' '2015-08-13 00:00:00']

Унікальні значення в колонці match_api_id:
[ 492473  492474  492475 ... 1992093 1992094 1992095]

Унікальні значення в колонці home_team_api_id:
[  9987  10000   9984   9991   7947   8203   9999   4049  10001   8342
   9985   9994   9996  

Унікальні значення в колонці B365H:
[ 1.73  1.95  2.38  1.44  5.    4.75  2.1   3.2   2.25  1.3   2.6   1.91
  2.9   1.7   2.35  6.    4.    1.36  2.4   1.75  1.4   1.83  2.    2.7
  3.6   2.3   1.25  3.25  2.05  2.2   4.33  2.5   1.67  1.29  1.57  1.2
  2.88  2.62  1.53  1.5   8.    2.8   1.61  3.    1.45  3.4   1.33  1.65
  1.8   1.9   1.66  3.1   2.15  1.22  5.75  1.85  6.5   1.28  4.5    nan
  3.75  1.62  5.5   7.    1.14  1.18 11.    1.17  1.55  2.75  3.3   1.6
  5.25  3.5   2.63  4.2   2.45  2.65  3.8   1.13  9.5   2.55  3.9   7.5
  3.7  12.    2.37  1.72  4.8   8.5   2.87 10.    9.   13.    1.1  15.
  1.11  1.38  4.1   5.8   1.48  4.9   2.95  6.25  4.3   4.6   1.08  1.06
  1.09 17.    1.07 19.   21.    1.16  6.75  1.15  4.25  1.05  1.04 23.
 26.   14.  ]

Унікальні значення в колонці B365D:
[ 3.4   3.2   3.3   3.75  3.5   3.25  5.25  4.75  4.33  4.5   4.2   3.6
  6.    4.    3.8   6.5   5.5   5.    5.75  3.1    nan  7.5   7.    3.9
  3.7   4.1   8.    8.5   4.6   3.   10.    9. 

In [14]:
# database League
league = pd.read_sql(
    """SELECT * FROM League;""", conn)

league

id  country_id                      name
0       1           1    Belgium Jupiler League
1    1729        1729    England Premier League
2    4769        4769            France Ligue 1
3    7809        7809     Germany 1. Bundesliga
4   10257       10257             Italy Serie A
5   13274       13274    Netherlands Eredivisie
6   15722       15722        Poland Ekstraklasa
7   17642       17642  Portugal Liga ZON Sagres
8   19694       19694   Scotland Premier League
9   21518       21518           Spain LIGA BBVA
10  24558       24558  Switzerland Super League

In [15]:
leagues = pd.read_sql("""SELECT *
                        FROM League
                        JOIN Country ON Country.id = League.country_id;""", conn)
leagues

id  country_id                      name     id         name
0       1           1    Belgium Jupiler League      1      Belgium
1    1729        1729    England Premier League   1729      England
2    4769        4769            France Ligue 1   4769       France
3    7809        7809     Germany 1. Bundesliga   7809      Germany
4   10257       10257             Italy Serie A  10257        Italy
5   13274       13274    Netherlands Eredivisie  13274  Netherlands
6   15722       15722        Poland Ekstraklasa  15722       Poland
7   17642       17642  Portugal Liga ZON Sagres  17642     Portugal
8   19694       19694   Scotland Premier League  19694     Scotland
9   21518       21518           Spain LIGA BBVA  21518        Spain
10  24558       24558  Switzerland Super League  24558  Switzerland

In [30]:
# matches FC Barcelona
detailed_matches = pd.read_sql("""SELECT Match.id, 
                                        League.name AS league_name,                                         
                                        season, 
                                        stage, 
                                        date,
                                        HT.team_long_name AS  home_team,
                                        AT.team_long_name AS away_team,
                                        home_team_goal, 
                                        away_team_goal                                        
                                FROM Match
                                JOIN Country on Country.id = Match.country_id
                                JOIN League on League.id = Match.league_id
                                LEFT JOIN Team AS HT ON HT.team_api_id = Match.home_team_api_id
                                LEFT JOIN Team AS AT ON AT.team_api_id = Match.away_team_api_id
                                WHERE (HT.team_long_name = 'FC Barcelona' OR AT.team_long_name = 'FC Barcelona')
                                ORDER by date;""", conn)
detailed_matches


id      league_name     season  stage                 date  \
0    21521  Spain LIGA BBVA  2008/2009      1  2008-08-31 00:00:00   
1    21630  Spain LIGA BBVA  2008/2009      2  2008-09-13 00:00:00   
2    21738  Spain LIGA BBVA  2008/2009      3  2008-09-21 00:00:00   
3    21842  Spain LIGA BBVA  2008/2009      4  2008-09-24 00:00:00   
4    21853  Spain LIGA BBVA  2008/2009      5  2008-09-27 00:00:00   
..     ...              ...        ...    ...                  ...   
299  24451  Spain LIGA BBVA  2015/2016     34  2016-04-20 00:00:00   
300  24462  Spain LIGA BBVA  2015/2016     35  2016-04-23 00:00:00   
301  24472  Spain LIGA BBVA  2015/2016     36  2016-04-30 00:00:00   
302  24483  Spain LIGA BBVA  2015/2016     37  2016-05-08 00:00:00   
303  24493  Spain LIGA BBVA  2015/2016     38  2016-05-14 00:00:00   

                     home_team               away_team  home_team_goal  \
0                  CD Numancia            FC Barcelona               1   
1                 FC Barcelona        Racing Santander               1   
2       Real Sporting de Gijón            FC Barcelona               1   
3                 FC Barcelona     Real Betis Balompié               3   
4                 RCD Espanyol            FC Barcelona               1   
..                         ...                     ...             ...   
299  RC Deportivo de La Coruña            FC Barcelona               0   
300               FC Barcelona  Real Sporting de Gijón               6   
301        Real Betis Balompié            FC Barcelona               0   
302               FC Barcelona            RCD Espanyol               5   
303                 Granada CF            FC Barcelona               0   

     away_team_goal  
0                 0  
1                 1  
2                 6  
3                 2  
4                 2  
..              ...  
299               8  
300               0  
301               2  
302               0  
303               3  

[304 rows x 9 columns]

In [16]:
league.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   id          11 non-null     int64 
 1   country_id  11 non-null     int64 
 2   name        11 non-null     object
dtypes: int64(2), object(1)
memory usage: 392.0+ bytes


In [17]:
for column in league.columns:
    unique_values = league[column].unique()
    print(f"Унікальні значення в колонці {column}:\n{unique_values}\n")

Унікальні значення в колонці id:
[    1  1729  4769  7809 10257 13274 15722 17642 19694 21518 24558]

Унікальні значення в колонці country_id:
[    1  1729  4769  7809 10257 13274 15722 17642 19694 21518 24558]

Унікальні значення в колонці name:
['Belgium Jupiler League' 'England Premier League' 'France Ligue 1'
 'Germany 1. Bundesliga' 'Italy Serie A' 'Netherlands Eredivisie'
 'Poland Ekstraklasa' 'Portugal Liga ZON Sagres' 'Scotland Premier League'
 'Spain LIGA BBVA' 'Switzerland Super League']



In [18]:
# database Country
countries = pd.read_sql(
    """SELECT * FROM Country;""", conn)

countries

id         name
0       1      Belgium
1    1729      England
2    4769       France
3    7809      Germany
4   10257        Italy
5   13274  Netherlands
6   15722       Poland
7   17642     Portugal
8   19694     Scotland
9   21518        Spain
10  24558  Switzerland

In [19]:
# database Team
team = pd.read_sql(
    """SELECT * FROM Team;""", conn)

team

id  team_api_id  team_fifa_api_id      team_long_name team_short_name
0        1         9987             673.0            KRC Genk             GEN
1        2         9993             675.0        Beerschot AC             BAC
2        3        10000           15005.0    SV Zulte-Waregem             ZUL
3        4         9994            2007.0    Sporting Lokeren             LOK
4        5         9984            1750.0   KSV Cercle Brugge             CEB
..     ...          ...               ...                 ...             ...
294  49479        10190             898.0       FC St. Gallen             GAL
295  49837        10191            1715.0             FC Thun             THU
296  50201         9777             324.0         Servette FC             SER
297  50204         7730            1862.0  FC Lausanne-Sports             LAU
298  51606         7896               NaN              Lugano             LUG

[299 rows x 5 columns]

In [20]:
team.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   id                299 non-null    int64  
 1   team_api_id       299 non-null    int64  
 2   team_fifa_api_id  288 non-null    float64
 3   team_long_name    299 non-null    object 
 4   team_short_name   299 non-null    object 
dtypes: float64(1), int64(2), object(2)
memory usage: 11.8+ KB


In [20]:
for column in team.columns:
    unique_values = team[column].unique()
    print(f"Унікальні значення в колонці {column}:\n{unique_values}\n")

In [21]:
# filter for 'team_long_name'
filtered_data =  team[team['team_long_name'] == 'FC Barcelona']
print(filtered_data)

        id  team_api_id  team_fifa_api_id team_long_name team_short_name
258  43042         8634             241.0   FC Barcelona             BAR


In [9]:
team_attributes = pd.read_sql(
    """SELECT * FROM Team_Attributes;""", conn)

team_attributes


id  team_fifa_api_id  team_api_id                 date  \
0        1               434         9930  2010-02-22 00:00:00   
1        2               434         9930  2014-09-19 00:00:00   
2        3               434         9930  2015-09-10 00:00:00   
3        4                77         8485  2010-02-22 00:00:00   
4        5                77         8485  2011-02-22 00:00:00   
...    ...               ...          ...                  ...   
1453  1454             15005        10000  2011-02-22 00:00:00   
1454  1455             15005        10000  2012-02-22 00:00:00   
1455  1456             15005        10000  2013-09-20 00:00:00   
1456  1457             15005        10000  2014-09-19 00:00:00   
1457  1458             15005        10000  2015-09-10 00:00:00   

      buildUpPlaySpeed buildUpPlaySpeedClass  buildUpPlayDribbling  \
0                   60              Balanced                   NaN   
1                   52              Balanced                  48.0   
2                   47              Balanced                  41.0   
3                   70                  Fast                   NaN   
4                   47              Balanced                   NaN   
...                ...                   ...                   ...   
1453                52              Balanced                   NaN   
1454                54              Balanced                   NaN   
1455                54              Balanced                   NaN   
1456                54              Balanced                  42.0   
1457                54              Balanced                  42.0   

     buildUpPlayDribblingClass  buildUpPlayPassing buildUpPlayPassingClass  \
0                       Little                  50                   Mixed   
1                       Normal                  56                   Mixed   
2                       Normal                  54                   Mixed   
3                       Little                  70                    Long   
4                       Little                  52                   Mixed   
...                        ...                 ...                     ...   
1453                    Little                  52                   Mixed   
1454                    Little                  51                   Mixed   
1455                    Little                  51                   Mixed   
1456                    Normal                  51                   Mixed   
1457                    Normal                  51                   Mixed   

      ... chanceCreationShooting  chanceCreationShootingClass  \
0     ...                     55                       Normal   
1     ...                     64                       Normal   
2     ...                     64                       Normal   
3     ...                     70                         Lots   
4     ...                     52                       Normal   
...   ...                    ...                          ...   
1453  ...                     53                       Normal   
1454  ...                     50                       Normal   
1455  ...                     32                       Little   
1456  ...                     32                       Little   
1457  ...                     32                       Little   

     chanceCreationPositioningClass  defencePressure defencePressureClass  \
0                         Organised               50               Medium   
1                         Organised               47               Medium   
2                         Organised               47               Medium   
3                         Organised               60               Medium   
4                         Organised               47               Medium   
...                             ...              ...                  ...   
1453                      Organised               46               Medium   
1454                      Organised     

In [10]:
team_attributes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1458 entries, 0 to 1457
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   id                              1458 non-null   int64  
 1   team_fifa_api_id                1458 non-null   int64  
 2   team_api_id                     1458 non-null   int64  
 3   date                            1458 non-null   object 
 4   buildUpPlaySpeed                1458 non-null   int64  
 5   buildUpPlaySpeedClass           1458 non-null   object 
 6   buildUpPlayDribbling            489 non-null    float64
 7   buildUpPlayDribblingClass       1458 non-null   object 
 8   buildUpPlayPassing              1458 non-null   int64  
 9   buildUpPlayPassingClass         1458 non-null   object 
 10  buildUpPlayPositioningClass     1458 non-null   object 
 11  chanceCreationPassing           1458 non-null   int64  
 12  chanceCreationPassingClass      14

In [11]:
team_attributes.columns

Index(['id', 'team_fifa_api_id', 'team_api_id', 'date', 'buildUpPlaySpeed',
       'buildUpPlaySpeedClass', 'buildUpPlayDribbling',
       'buildUpPlayDribblingClass', 'buildUpPlayPassing',
       'buildUpPlayPassingClass', 'buildUpPlayPositioningClass',
       'chanceCreationPassing', 'chanceCreationPassingClass',
       'chanceCreationCrossing', 'chanceCreationCrossingClass',
       'chanceCreationShooting', 'chanceCreationShootingClass',
       'chanceCreationPositioningClass', 'defencePressure',
       'defencePressureClass', 'defenceAggression', 'defenceAggressionClass',
       'defenceTeamWidth', 'defenceTeamWidthClass',
       'defenceDefenderLineClass'],
      dtype='object')


* 'id' - Ідентифікатор
* 'team_fifa_api_id' - Ідентифікатор команди FIFA
* 'team_api_id' - Ідентифікатор команди
* 'date' - Дата
* 'buildUpPlaySpeed' - Швидкість будівництва гри
* 'buildUpPlaySpeedClass' - Клас швидкості будівництва гри
* 'buildUpPlayDribbling' - Дриблінг будівництва гри
* 'buildUpPlayDribblingClass' - Клас дриблінгу будівництва гри
* 'buildUpPlayPassing' - Передачі будівництва гри
* 'buildUpPlayPassingClass' - Клас передач будівництва гри
* 'buildUpPlayPositioningClass' - Клас позиціонування будівництва гри
* 'chanceCreationPassing' - Передачі для створення шансів
* 'chanceCreationPassingClass' - Клас передач для створення шансів
* 'chanceCreationCrossing' - Подачі для створення шансів
* 'chanceCreationCrossingClass' - Клас подач для створення шансів
* 'chanceCreationShooting' - Удари для створення шансів
* 'chanceCreationShootingClass' - Клас ударів для створення шансів
* 'chanceCreationPositioningClass' - Клас позиціонування для створення шансів
* 'defencePressure' - Тиск захисту
* 'defencePressureClass' - Клас тиску захисту
* 'defenceAggression' - Агресія захисту
* 'defenceAggressionClass' - Клас агресії захисту
* 'defenceTeamWidth' - Ширина оборонної лінії
* 'defenceTeamWidthClass' - Клас ширини оборонної лінії
* 'defenceDefenderLineClass' - Клас лінії захисту
